import { QuizQuestion } from '../types/quiz';

export const questions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Is your hemoglobin level below 12.5 g/dL?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 30,
    blockReason: 'Low hemoglobin level (below 12.5 g/dL)',
    pointsDeduction: 15,
  },
  {
    id: 'q2',
    question: 'Have you traveled to a malaria-endemic zone in the last 3 months?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 90,
    blockReason: 'Recent travel to malaria-endemic zone',
    pointsDeduction: 20,
  },
  {
    id: 'q3',
    question: 'Are you currently taking antibiotics?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 14,
    blockReason: 'Currently on antibiotics',
    pointsDeduction: 10,
  },
  {
    id: 'q4',
    question: 'Are you HIV positive?',
    answerType: 'boolean',
    blockType: 'PERMANENT',
    blockReason: 'HIV positive',
    pointsDeduction: 100,
  },
  {
    id: 'q5',
    question: 'Have you been diagnosed with Hepatitis B or Hepatitis C?',
    answerType: 'boolean',
    blockType: 'PERMANENT',
    blockReason: 'Hepatitis B or C diagnosis',
    pointsDeduction: 100,
  },
  {
    id: 'q6',
    question: 'Have you had a tattoo or piercing in the last 6 months?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 180,
    blockReason: 'Recent tattoo or piercing within 6 months',
    pointsDeduction: 15,
  },
  {
    id: 'q7',
    question: 'Are you currently pregnant or breastfeeding?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 365,
    blockReason: 'Currently pregnant or breastfeeding',
    pointsDeduction: 20,
  },
  {
    id: 'q8',
    question: 'Have you received any vaccination in the last 4 weeks?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 28,
    blockReason: 'Recent vaccination within 4 weeks',
    pointsDeduction: 10,
  },
  {
    id: 'q9',
    question: 'Do you weigh less than 50 kg?',
    answerType: 'boolean',
    blockType: 'PERMANENT',
    blockReason: 'Body weight below 50 kg',
    pointsDeduction: 100,
  },
  {
    id: 'q10',
    question: 'Have you undergone surgery in the last 6 months?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 180,
    blockReason: 'Recent surgery within 6 months',
    pointsDeduction: 15,
  },
  {
    id: 'q11',
    question: 'Have you consumed alcohol in the last 24 hours?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 1,
    blockReason: 'Alcohol consumption within the last 24 hours',
    pointsDeduction: 5,
  },
  {
    id: 'q12',
    question: 'Do you have a history of cancer?',
    answerType: 'boolean',
    blockType: 'PERMANENT',
    blockReason: 'History of cancer',
    pointsDeduction: 100,
  },
  {
    id: 'q13',
    question: 'Do you have uncontrolled high blood pressure?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 90,
    blockReason: 'Uncontrolled high blood pressure',
    pointsDeduction: 15,
  },
  {
    id: 'q14',
    question: 'Have you been diagnosed with a heart disease?',
    answerType: 'boolean',
    blockType: 'PERMANENT',
    blockReason: 'Heart disease diagnosis',
    pointsDeduction: 100,
  },
  {
    id: 'q15',
    question: 'Have you had a cold or flu in the last 2 weeks?',
    answerType: 'boolean',
    blockType: 'TEMPORARY',
    blockDuration: 14,
    blockReason: 'Recent cold or flu within 2 weeks',
    pointsDeduction: 5,
  },
];
